name: CI Minishell

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libreadline-dev
        sudo apt-get install -y norminette
        sudo apt_get install -y valgrind

    - name: Build
      run: make

    - name: Run norm
      run: make norm

    - name: Run valgrind
      run: make val
